master pull from Xm dev
APSIS-ANALYSIS/PERIGEE pull request #100
Opened 2023-10-10 03:52 UTC by Goldeninscriptions

2023-10-10 04:56 UTC, ju-liu commented on examples/ruc_fsi/CMakeLists.txt
> -  ${perigee_source}/Mesh/ElemBC_3D_wall.cpp
ElemBC_3D_wall去哪了？

2023-10-10 04:58 UTC, ju-liu requested changes

2023-10-10 04:58 UTC, ju-liu commented on src/Mesh/Gmsh_FileIO.cpp
> +        {
对齐

2023-10-10 05:18 UTC, Goldeninscriptions commented on examples/ruc_fsi/CMakeLists.txt
> -  ${perigee_source}/Mesh/ElemBC_3D_wall.cpp
resolve conflict 的时候不小心摘掉了

2023-10-10 06:22 UTC, ju-liu commented
@Syj-0525 你跟黄宣铭交流一下，学习一下gmsh里面施加periodic bc的方法，然后实测一下这个。

2023-10-10 10:02 UTC, ju-liu requested changes

2023-10-10 10:02 UTC, ju-liu commented on examples/ruc_fsi/CMakeLists.txt
>    ${perigee_source}/Mesh/ElemBC_3D_tet.cpp
这里对吗？请再核实
@Goldeninscriptions

2023-10-10 12:07 UTC, Syj-0525 reviewed
@ju-liu 老师，我测试后周期边界是没有问题的。但注意到，由于删掉了老的(不加名字输出的)write_quadratic_sur_vtu和write_vtp函数，现在example中的fsi, ruc_fsi以及ns都无法编译通过

2023-10-11 02:36 UTC, ju-liu approved these changes

2023-10-11 02:36 UTC, merged