Sun dev
APSIS-ANALYSIS/PERIGEE pull request #114
Opened 2023-11-01 01:45 UTC by Syj-0525

为ns兼容了hex单元的后处理

2023-11-01 09:57 UTC, ju-liu approved these changes
需要当面交流一下 就可以合并。目测没有大的问题。

2023-11-01 11:34 UTC, Goldeninscriptions approved these changes

2023-11-02 00:13 UTC, ju-liu requested changes

2023-11-02 00:13 UTC, ju-liu commented on include/QuadPts_vis_quad9.hpp
> +    std::vector<double> qp, qw;
使用静态的数组。

2023-11-02 00:13 UTC, ju-liu commented on include/QuadPts_vis_quad4.hpp
> +    std::vector<double> qp, qw;
使用静态的数组。

2023-11-02 01:27 UTC, ju-liu requested changes

2023-11-02 01:27 UTC, ju-liu commented on include/QuadPts_vis_quad4.hpp
> +    virtual int get_num_quadPts() const {return 2;}
4?

2023-11-02 01:27 UTC, ju-liu commented on include/QuadPts_vis_quad9.hpp
> +    virtual int get_num_quadPts() const {return 3;}
9>

2023-11-02 03:02 UTC, Syj-0525 commented on include/QuadPts_vis_quad9.hpp
> +    virtual int get_num_quadPts() const {return 3;}
我在  1945ce19277ebcc1c2e74beea286dbf2553daae9 提交里主要作了两个修改：
1、将quad9/4 重命名为 quad
2、为hex和quad的QuadPts相关类添加了返回某一方向积分点的成员函数。由于调用Quad类时，都是调用的基类指针，因此，在IQuadPts基类里也作为虚函数进行了定义

2023-11-03 03:57 UTC, ju-liu approved these changes

2023-11-03 03:58 UTC, merged

2023-11-03 04:34 UTC, Goldeninscriptions commented on examples/ns/vis_602_p2_wss.cpp
range_generator 重排过了 surface_ien 才能使得 “The quad element's ii-th basis corresponds to the hex element's id_range[ii]-th basis”，才能找到正确的法向量。现在 surface element又用回了没有重排的 ien

2023-11-03 04:38 UTC, Goldeninscriptions commented on examples/ns/vis_602_p2_wss.cpp
对一阶单元应该没有影响，对于二阶单元是不是会影响 outnormal[ii] 的顺序的正确性，然后影响到 
// obtain the hex element's id_range[qua] node's outward normal vector @ju-liu @Syj-0525

2023-11-03 04:38 UTC, Goldeninscriptions commented on examples/ns/vis_602_p2_wss.cpp
> -
这个确实没用

2023-11-03 04:42 UTC, Syj-0525 commented on examples/ns/vis_602_p2_wss.cpp
这里测试调整range_generator中sur_ien顺序后，对wss结果没有影响

2023-11-03 04:44 UTC, Syj-0525 commented on examples/ns/vis_602_p2_wss.cpp
这里这么修改后，经过测试修改前后601和602的wss后处理结果无变化

2023-11-03 04:49 UTC, ju-liu commented on examples/ns/vis_602_p2_wss.cpp
我理解是后面的取法向量用的是inteerior point来确定外方向。这与我们前面用的不一样，也不依赖节点的特定顺序。

我不知道有没有回答你的问题。 @Goldeninscriptions

2023-11-03 04:51 UTC, Syj-0525 commented on examples/ns/vis_602_p2_wss.cpp
这里 const double nx = outnormal[qua].x(); 看起来还是 obtain the quad elements qua-th node's outward normal vector