Elastodynamics
APSIS-ANALYSIS/PERIGEE pull request #117
Opened 2023-11-07 11:07 UTC by SeaVegetable

add an example of elastodynamics

2023-11-08 05:43 UTC, ju-liu requested changes

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/include/PGAssem_Elastodynamics_GenAlpha.hpp
> +
add comment here to describe the file.

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/include/PLocAssem_Transport_GenAlpha.hpp
> +    virtual int get_dof() const {return 1;}
为什么我们以前会在transport的问题里dof设置为3？

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/include/PTime_LinearPDE_Solver.hpp
> +
减去一行。我们一般空一行。

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/include/Post_error_elastodynamics.hpp
> +  double get_manu_sol_error(
这里名字起作 get_manu_sol_errorL2?跟下面对应上。

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/src/PGAssem_Elastodynamics_GenAlpha.cpp
> +  if(num_ebc>0) snLocBas = part_ebc -> get_cell_nLocBas(0);
感觉可以将snLocBas设为const member data，初始化用？：。

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/src/VTK_Writer_Elastodynamics.cpp
> +  PetscPrintf(PETSC_COMM_WORLD, "-- Clean gridData object.\n");
use SYS_T::commPrint

2023-11-08 05:43 UTC, ju-liu commented on examples/linearPDE/src/PGAssem_Elastodynamics_GenAlpha.cpp
> +
需要检查dof 的匹配性。参考ns/src/PGAssem_NS_FEM.cpp

2023-11-08 05:44 UTC, ju-liu commented on examples/linearPDE/include/PLocAssem_Transport_GenAlpha.hpp
> +      return 0.0;
两个都要改。

2023-11-09 10:56 UTC, ju-liu requested changes

2023-11-09 10:56 UTC, ju-liu commented on examples/linearPDE/include/PGAssem_Transport_GenAlpha.hpp
> +#define PGASSEM_ELASTODYNAMICS_GENALPHA_HPP
This is wrong.

2023-11-09 10:56 UTC, ju-liu commented on examples/linearPDE/include/PGAssem_Transport_GenAlpha.hpp
> +#define PGASSEM_ELASTODYNAMICS_GENALPHA_HPP
This whole file needs to be updated.

2023-11-10 09:31 UTC, SeaVegetable commented on examples/linearPDE/src/PGAssem_Elastodynamics_GenAlpha.cpp
> +
老师好！这里遇到一些问题，driver中的Matrix_PETSc和PDNSolution都是依赖于pNode中的dof（dofNum，对于弹性动力学，取值为6）生成的，但是我们在PGAssem中的获取局部solution依赖于dofMat（对于弹性动力学，取值为3）。我之前的做法是在预处理时就将输入文件preprocess.yml中dofNum设置为3，这种做法与fsi中的做法相同，并且可以通过PDNSolution_Elastodynamics构造函数中的检查（要求dofNum等于3）。但是，这种做法会导致dofNum与PLocAssem中的dof_sol不同，导致报错。

2023-11-17 00:15 UTC, ju-liu approved these changes

2023-11-17 00:36 UTC, merged