Make Matrix_SymPos_Dense an independent class
APSIS-ANALYSIS/PERIGEE pull request #121
Opened 2023-11-09 12:17 UTC by davidluojw

We should not make it a derived class of Matrix_Dense as it does not need the permutation vector pp at all. Logically, making it an independent class will make things easier and cleaner.

2023-11-09 14:11 UTC, ju-liu requested changes

2023-11-10 03:23 UTC, ju-liu approved these changes

2023-11-10 03:23 UTC, ju-liu commented on include/Math_Tools.hpp
> +        }
我做了一个对称化，至少保证矩阵是对称的。

2023-11-10 07:06 UTC, Syj-0525 approved these changes

2023-11-10 07:15 UTC, merged